# Generated by Django 3.2.16 on 2024-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20241210_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для публикации.', null=True, upload_to='posts/', verbose_name='Изображение публикации'),
        ),
    ]
