# Generated by Django 3.2.16 on 2024-12-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Максимум 500 символов', max_length=256, verbose_name='Текст комментария'),
        ),
    ]
